module.exports = [
    {
        id: '000001',
        name: 'Bob Goodman',
        birthday: '1999-01-23',
        email: 'Bb4328096@gmail.com',
        phone: '0414765432',
        address: '187 Flinders Ln, Melbourne VIC 3000.',
        bio: '5-year heart disease and pollen allergy.',
        supportMessage: 'Hi Bob - great day for exercising! See you later 😊',
        healthData: [
            {
                date: '03/13/2020',
                bgLevel: '10.8',
                weight: '70',
                insulinTaken: '1',
                exercise: '5348',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '11.0',
                weight: '58',
                insulinTaken: '',
                exercise: '2626',
            },
            {
                date: '03/13/2020',
                bgLevel: '10.8',
                weight: '70',
                insulinTaken: '1',
                exercise: '5348',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '',
                weight: '58',
                insulinTaken: '1',
                exercise: '2626',
            },
            {
                date: '03/13/2020',
                bgLevel: '10.8',
                weight: '70',
                insulinTaken: '1',
                exercise: '5348',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '11.0',
                weight: '58',
                insulinTaken: '1',
                exercise: '2626',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '11.0',
                weight: '58',
                insulinTaken: '1',
                exercise: '2626',
            },
            {
                date: '03/13/2020',
                bgLevel: '',
                weight: '70',
                insulinTaken: '1',
                exercise: '5348',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '11.0',
                weight: '58',
                insulinTaken: '1',
                exercise: '2626',
            },
            {
                date: '03/13/2020',
                bgLevel: '10.8',
                weight: '70',
                insulinTaken: '1',
                exercise: '',
            },
            {
                date: '03/12/2020',
                bgLevel: '10.9',
                weight: '65',
                insulinTaken: '1',
                exercise: '10004',
            },
            {
                date: '03/11/2020',
                bgLevel: '11.0',
                weight: '58',
                insulinTaken: '1',
                exercise: '2626',
            },
        ],
    },
    {
        id: '000002',
        name: 'Bob2',
        birthday: '1999-02-31',
        email: 'Bb43280962@gmail.com',
        phone: '04147654322',
        address: '187 Flinders Ln, Melbourne VIC 30002.',
        bio: '5-year heart disease and pollen allergy2.',
    },
]
